# Generated by Django 5.0.4 on 2024-04-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_userimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
