# Generated by Django 5.0.4 on 2024-04-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImages',
        ),
    ]
